force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document_Version__c.field-meta.xml
<CustomField>
    <fullName>Document_Version__c</fullName>
    <label>Document Version</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/customSearchSobjectLWC.cls
public with sharing class customSearchSobjectLWC {


@AuraEnabled(cacheable=true)
public static list<document__C> getDocumentList(string searchKey) {
    string searchKeyword = '%' + searchKey + '%';
    
   // create contact list to store search result 
    list<document__C> documentListRecord = new list<document__C>();
 
   // query contact records
    for(document__C docObj : [Select id,Name,Document_Version__C,Document_Category__C
                        From Document__C
                        WHERE name LIKE : searchKeyword ORDER BY Name ASC]){
        documentListRecord.add(docObj);
    }
    
     if(documentListRecord.size() == 0){
        throw new AuraHandledException('No Record Found..'); 
     }
     
    return documentListRecord;
}
}